module.exports = {

  DEFAULT_MAX_PLAYERS: 6,
  MIN_PLAYERS: 3,
  MAX_PLAYERS_LIMIT: 10,

  DEFAULT_ROUND_DURATION: 30000,
  MIN_ROUND_DURATION: 10000,
  MAX_ROUND_DURATION: 30000,

  PREPARE_TIME: 3000,
  ROOM_ID_LENGTH: 6,
  SOUNDS_FOLDER: "./public/sounds",
};
